// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9iq1xktYyDCxviHNk13Xew
// Component: xgAR9nZqp26t

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: HdFOLY6TrBds/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 9iq1xktYyDCxviHNk13Xew/projectcss
import sty from "./PlasmicSomeComponent.module.css"; // plasmic-import: xgAR9nZqp26t/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: nMLQe1Nr3ocm/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: F4euiE62pj7r/icon

createPlasmicElementProxy;

export type PlasmicSomeComponent__VariantMembers = {};
export type PlasmicSomeComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicSomeComponent__VariantsArgs;
export const PlasmicSomeComponent__VariantProps = new Array<VariantPropType>();

export type PlasmicSomeComponent__ArgsType = {};
type ArgPropType = keyof PlasmicSomeComponent__ArgsType;
export const PlasmicSomeComponent__ArgProps = new Array<ArgPropType>();

export type PlasmicSomeComponent__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultSomeComponentProps {
  className?: string;
}

const $$ = {};

function PlasmicSomeComponent__RenderFunc(props: {
  variants: PlasmicSomeComponent__VariantsArgs;
  args: PlasmicSomeComponent__ArgsType;
  overrides: PlasmicSomeComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Button className={classNames("__wab_instance", sty.button__t4CkB)} />

      <Button className={classNames("__wab_instance", sty.button__gPs4)} />

      <Button className={classNames("__wab_instance", sty.button__g9TQv)} />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSomeComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSomeComponent__VariantsArgs;
    args?: PlasmicSomeComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSomeComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSomeComponent__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSomeComponent__ArgProps,
          internalVariantPropNames: PlasmicSomeComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSomeComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSomeComponent";
  } else {
    func.displayName = `PlasmicSomeComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicSomeComponent = Object.assign(
  // Top-level PlasmicSomeComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicSomeComponent
    internalVariantProps: PlasmicSomeComponent__VariantProps,
    internalArgProps: PlasmicSomeComponent__ArgProps
  }
);

export default PlasmicSomeComponent;
/* prettier-ignore-end */
